### ISSUE TITLE
2D version of RORPO_multiscale_usage?

### ISSUE THREAD

**Issue by joseabernal** [path-openings/RORPO#21]
Hi,

Is there a 2D version of RORPO? I saw there’s a paper about it but couldn’t find a parameter for it in the help of RORPO_multiscale_usage. 

Best regards,

Jose

**Comment by omerveille** [comment]
Hi,
Yes, a 2D version of RORPO is available in C++, however it is not included in this repo. You may find the code and its description on IPOL: https://www.ipol.im/pub/art/2017/207/

Best regards,
Odyssée

**Comment by joseabernal** [comment]
Fantastic, thank you for your prompt response.
